#!/usr/bin/env python3
"""
SeaSlides Typst Slides - Error Message Helper

Provides user-friendly error messages and specific fix suggestions
for Typst compilation and project structure issues.
"""

import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


class ErrorHelper:
    """Error message helper for Typst/Touying projects."""

    ERROR_SOLUTIONS: Dict[str, Dict] = {
        # ---- Project Structure ----
        'missing_main_typ': {
            'message': 'Missing main.typ file',
            'solutions': [
                'Create a main.typ file as the presentation entry point',
                'Use: python3 project_manager.py init <project_name>',
                'main.typ should #import the template and define slide content',
            ],
            'severity': 'error'
        },
        'missing_template': {
            'message': 'Missing template.typ file',
            'solutions': [
                'Create a template.typ file with theme definitions',
                'Or use a built-in/universe/user theme via #import "@preview/touying:0.7.4"',
                'Template should contain ZERO content text — only styles and layouts',
            ],
            'severity': 'warning'
        },
        'missing_spec': {
            'message': 'Missing design specification file',
            'solutions': [
                'Create a content_design_spec.md file',
                'Include: page format, color scheme, font specs, layout specs, content outline',
                'Refer to the design specification generated by the Strategist role',
            ],
            'severity': 'warning'
        },
        'missing_directory': {
            'message': 'Missing required directory',
            'solutions': [
                'Create the directory: mkdir -p <directory>',
                'Standard directories: assets/, output/',
            ],
            'severity': 'warning'
        },
        'missing_date_suffix': {
            'message': 'Project directory missing date suffix',
            'solutions': [
                'Rename the project directory to add a date suffix: _YYYYMMDD',
                'Format: {project_name}_{format}_{YYYYMMDD}',
                'Example: my_project_ppt169_20260413',
            ],
            'severity': 'warning'
        },
        # ---- Typst Compilation ----
        'unknown_function': {
            'message': 'Unknown function or variable',
            'solutions': [
                'Check if the function/variable name is spelled correctly',
                'Ensure the function is imported: #import "@preview/module:version"',
                'Check if the function is defined before use',
                'Verify the module version is correct',
            ],
            'severity': 'error'
        },
        'missing_argument': {
            'message': 'Missing required argument',
            'solutions': [
                'Check the function signature for required arguments',
                'Provide all required positional or named arguments',
                'Review the documentation for the correct argument order',
            ],
            'severity': 'error'
        },
        'type_error': {
            'message': 'Type mismatch',
            'solutions': [
                'Verify the argument types match the expected types',
                'Check if you need to convert the type (e.g., using str(), int())',
                'Review the function documentation for type requirements',
            ],
            'severity': 'error'
        },
        'syntax_error': {
            'message': 'Syntax error',
            'solutions': [
                'Check for missing or extra parentheses, brackets, or braces',
                'Verify proper syntax for the construct you are using',
                'Look for unclosed strings or comments',
            ],
            'severity': 'error'
        },
        'file_not_found': {
            'message': 'File not found',
            'solutions': [
                'Verify the file path is correct',
                'Check if the file exists in the project directory',
                'Use relative paths from the main.typ file',
                'Ensure the file is not in a hidden directory',
            ],
            'severity': 'error'
        },
        'font_not_found': {
            'message': 'Font not found',
            'solutions': [
                'Install the required font on your system',
                'Check if the font name is spelled correctly',
                'Use a standard font that is available cross-platform',
                'Specify the font file path explicitly',
            ],
            'severity': 'error'
        },
        'overflow': {
            'message': 'Content overflow detected',
            'solutions': [
                'Reduce the amount of content on the slide',
                'Adjust font size or spacing',
                'Use a smaller image or resize existing images',
                'Split content across multiple slides',
            ],
            'severity': 'warning'
        },
        'unclosed_element': {
            'message': 'Unclosed element or unexpected end of input',
            'solutions': [
                'Check for unclosed brackets, parentheses, or braces',
                'Verify all #show or #let directives are properly closed',
                'Look for missing closing tags in markup',
            ],
            'severity': 'error'
        },
        'package_not_found': {
            'message': 'Package not found or version mismatch',
            'solutions': [
                'Check the package name and version in the #import statement',
                'Ensure you have internet access for package download',
                'Try: typst update to refresh the package cache',
                'Check https://typst.app/universe for available packages',
            ],
            'severity': 'error'
        },
        # ---- TCS Violations ----
        'inline_style_in_main': {
            'message': 'Inline style detected in main.typ (TCS violation)',
            'solutions': [
                'Move raw color definitions (rgb()) and ad-hoc styled blocks (block(fill:, stroke:)) to template.typ',
                'main.typ may use structural layout (grid, align, #v, #text(size:), #pad) but NOT raw visual styling',
                'Use template component functions instead of inline block(fill:, stroke:, inset:, radius:)',
                'Reference: references/shared-standards.md',
            ],
            'severity': 'warning'
        },
        'content_in_template': {
            'message': 'Content text detected in template.typ (TCS violation)',
            'solutions': [
                'Move all content text to main.typ',
                'template.typ should contain ZERO content text',
                'Only styles, layouts, and reusable components belong in template.typ',
            ],
            'severity': 'warning'
        },
    }

    # Regex patterns for auto-diagnosis from Typst error output
    _ERROR_PATTERNS: Dict[str, List[str]] = {
        'unknown_function': [
            r'error: unknown function',
            r'error: unknown variable',
        ],
        'missing_argument': [
            r'error: missing argument',
            r'error: expected .*? arguments, found',
        ],
        'type_error': [
            r'error: type mismatch',
            r'error: expected \w+, found \w+',
        ],
        'syntax_error': [
            r'error: unexpected',
            r'error: expected .+? found',
        ],
        'file_not_found': [
            r'error: file not found',
            r'error: cannot access file',
        ],
        'font_not_found': [
            r'error: font not found',
            r'error: could not find font',
        ],
        'overflow': [
            r'warning: content overflow',
            r'error: content does not fit',
        ],
        'unclosed_element': [
            r'error: unclosed',
            r'error: unexpected end of input',
        ],
        'package_not_found': [
            r'error: package not found',
            r'error: failed to download',
        ],
    }

    @classmethod
    def get_solution(cls, error_type: str, context: Optional[Dict] = None) -> Dict:
        """Get the solution for an error type."""
        if error_type in cls.ERROR_SOLUTIONS:
            solution = cls.ERROR_SOLUTIONS[error_type].copy()
            if context:
                solution = cls._customize_solution(solution, context)
            return solution

        return {
            'message': 'Unknown error',
            'solutions': [
                'Review the error message for specific details',
                'Check the Typst documentation for the feature you are using',
                'Ensure you are using a compatible version of Typst',
            ],
            'severity': 'error'
        }

    @classmethod
    def _customize_solution(cls, solution: Dict, context: Dict) -> Dict:
        """Customize solution based on context."""
        customized = solution.copy()

        if 'project_path' in context:
            project_path = context['project_path']
            customized['solutions'] = [
                s.replace('<project_path>', project_path).replace('<your_project>', project_path)
                for s in customized['solutions']
            ]

        if 'file_name' in context:
            customized['message'] = f"{customized['message']}: {context['file_name']}"

        if 'expected' in context and 'actual' in context:
            customized['message'] += f" (expected: {context['expected']}, actual: {context['actual']})"

        return customized

    @classmethod
    def diagnose_error(cls, error_message: str) -> Tuple[Optional[str], List[str]]:
        """Diagnose a Typst error message and provide suggestions."""
        error_message_lower = error_message.lower()

        for error_type, patterns in cls._ERROR_PATTERNS.items():
            for pattern in patterns:
                if re.search(pattern, error_message_lower):
                    solution = cls.ERROR_SOLUTIONS.get(error_type, {})
                    return error_type, solution.get('solutions', [])

        return None, [
            'Review the error message for specific details',
            'Check the Typst documentation for the feature you are using',
            'Ensure you are using a compatible version of Typst',
            'Try simplifying the problematic code',
        ]

    @classmethod
    def format_error_message(cls, error_type: str, context: Optional[Dict] = None) -> str:
        """Format error message for terminal output."""
        solution = cls.get_solution(error_type, context)
        lines = []

        severity_icon = "[ERROR]" if solution['severity'] == 'error' else "[WARN]"
        lines.append(f"{severity_icon} {solution['message']}")

        if solution['solutions']:
            lines.append("\nSuggested fixes:")
            for i, sol in enumerate(solution['solutions'], 1):
                lines.append(f"   {i}. {sol}")

        return "\n".join(lines)

    @classmethod
    def print_error(cls, error_type: str, context: Optional[Dict] = None) -> None:
        """Print formatted error message."""
        print(cls.format_error_message(error_type, context))

    @classmethod
    def get_all_error_types(cls) -> List[str]:
        """Get all supported error types."""
        return list(cls.ERROR_SOLUTIONS.keys())

    @classmethod
    def print_help(cls) -> None:
        """Print all error types and solutions."""
        print("SeaSlides Typst Slides - Error Types and Solutions\n")
        print("=" * 80)

        for error_type, info in cls.ERROR_SOLUTIONS.items():
            print(f"\n[{error_type}]")
            print(f"Message: {info['message']}")
            print(f"Severity: {info['severity']}")
            print("Solutions:")
            for i, sol in enumerate(info['solutions'], 1):
                print(f"  {i}. {sol}")
            print("-" * 80)


@dataclass(frozen=True)
class CommonIssue:
    """A structured, heuristic source-level issue.

    Static analysis is intentionally advisory/review-level. The Typst compiler
    is the authority for syntax; these checks must not pretend to parse Typst by
    counting brackets or by applying package-version rules across imports.
    """

    code: str
    severity: str
    message: str
    line: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        return {key: value for key, value in asdict(self).items() if value is not None}


def _line_for_match(content: str, match: re.Match) -> int:
    return content.count("\n", 0, match.start()) + 1


def _version_tuple(version: str) -> Tuple[int, int, int]:
    try:
        major, minor, patch = version.split(".", 2)
        return int(major), int(minor), int(patch)
    except (AttributeError, TypeError, ValueError):
        return 0, 0, 0


def _mask_literals_and_comments(
    content: str, preserve_import_strings: bool = False
) -> str:
    """Mask strings, raw blocks, and comments while preserving line numbers.

    When ``preserve_import_strings`` is set, package strings immediately after
    a real ``#import`` are retained so import-version checks can inspect them.
    Comments and raw text remain masked, including examples that look like an
    import directive.
    """
    chars = list(content)
    index = 0
    while index < len(content):
        if content.startswith("//", index):
            end = content.find("\n", index + 2)
            end = len(content) if end == -1 else end
        elif content.startswith("/*", index):
            close = content.find("*/", index + 2)
            end = len(content) if close == -1 else close + 2
        elif content[index] == '"':
            line_start = content.rfind("\n", 0, index) + 1
            prefix = content[line_start:index]
            if preserve_import_strings and re.match(r"^\s*#import\s*$", prefix):
                end = index + 1
                while end < len(content):
                    if content[end] == "\\":
                        end += 2
                        continue
                    if content[end] == '"':
                        end += 1
                        break
                    end += 1
                index = end
                continue
            end = index + 1
            while end < len(content):
                if content[end] == "\\":
                    end += 2
                    continue
                if content[end] == '"':
                    end += 1
                    break
                end += 1
        elif content[index] == "`":
            tick_count = 1
            while (
                index + tick_count < len(content)
                and content[index + tick_count] == "`"
            ):
                tick_count += 1
            marker = "`" * tick_count
            close = content.find(marker, index + tick_count)
            end = len(content) if close == -1 else close + tick_count
        else:
            index += 1
            continue

        for position in range(index, end):
            if chars[position] != "\n":
                chars[position] = " "
        index = end
    return "".join(chars)


def _call_arguments(content: str, opening_paren: int) -> Optional[str]:
    """Return a call's balanced argument text, or ``None`` when incomplete."""
    paren_depth = 1
    bracket_depth = 0
    brace_depth = 0
    index = opening_paren + 1
    while index < len(content):
        char = content[index]
        if char == "[":
            bracket_depth += 1
        elif char == "]":
            bracket_depth = max(0, bracket_depth - 1)
        elif char == "{":
            brace_depth += 1
        elif char == "}":
            brace_depth = max(0, brace_depth - 1)
        elif bracket_depth == 0 and brace_depth == 0 and char == "(":
            paren_depth += 1
        elif bracket_depth == 0 and brace_depth == 0 and char == ")":
            paren_depth -= 1
            if paren_depth == 0:
                return content[opening_paren + 1:index]
        index += 1
    return None


def _top_level_named_argument(arguments: str, name: str) -> Optional[str]:
    """Return a simple named argument without treating nested calls as peers."""
    depth = 0
    index = 0
    matcher = re.compile(r"\b%s\s*:" % re.escape(name))
    while index < len(arguments):
        char = arguments[index]
        if char in "([{":
            depth += 1
        elif char in ")]}":
            depth = max(0, depth - 1)
        elif depth == 0:
            match = matcher.match(arguments, index)
            if match:
                value_start = match.end()
                value_end = value_start
                value_depth = 0
                while value_end < len(arguments):
                    value_char = arguments[value_end]
                    if value_char in "([{":
                        value_depth += 1
                    elif value_char in ")]}":
                        if value_depth == 0:
                            break
                        value_depth -= 1
                    elif value_char == "," and value_depth == 0:
                        break
                    value_end += 1
                return arguments[value_start:value_end].strip()
        index += 1
    return None


def _analyze_stack_spacing(content: str) -> List[CommonIssue]:
    """Flag literal vertical stack spacings that merit visual review.

    Only an omitted direction or a literal ``ttb``/``btt`` is known to be
    vertical.  A dynamic direction is intentionally skipped: this source-level
    helper cannot resolve it safely. Positive spacing is intentionally left to
    rendered review because compact labels, dimension marks, and decorative
    primitives can legitimately use values below ordinary content spacing.
    """
    issues: List[CommonIssue] = []
    for match in re.finditer(r"\bstack\s*\(", content):
        opening_paren = content.find("(", match.start(), match.end())
        arguments = _call_arguments(content, opening_paren)
        if arguments is None:
            continue
        direction = _top_level_named_argument(arguments, "dir")
        if direction is not None and direction.strip() not in {"ttb", "btt"}:
            continue
        spacing = _top_level_named_argument(arguments, "spacing")
        if spacing is None:
            continue
        length_match = re.fullmatch(
            r"(-?[0-9]*\.?[0-9]+)\s*(?:em|pt|mm|cm|in)", spacing
        )
        if not length_match:
            continue
        value = float(length_match.group(1))
        if value < 0:
            issues.append(
                CommonIssue(
                    code="STACK_NEGATIVE_SPACING_REVIEW",
                    severity="review",
                    message=(
                        "Vertical stack uses negative spacing; inspect the rendered overlap "
                        "and confirm that it is intentional."
                    ),
                    line=_line_for_match(content, match),
                )
            )
        elif value == 0:
            issues.append(
                CommonIssue(
                    code="STACK_ZERO_SPACING_REVIEW",
                    severity="advisory",
                    message=(
                        "Vertical stack uses zero spacing. This is often an intentional "
                        "seamless primitive; inspect the rendered result for cramped content "
                        "or unintended seams."
                    ),
                    line=_line_for_match(content, match),
                )
            )
    return issues


def analyze_stack_spacing_file(file_path: str) -> List[CommonIssue]:
    """Analyze only stack spacing in a local Typst file.

    This focused entry point lets a theme demo audit its sibling template without
    applying entry-point-only import/show/TCS heuristics to that template.
    """
    try:
        content = Path(file_path).read_text(encoding="utf-8")
    except Exception as exc:
        return [
            CommonIssue(
                code="STACK_ANALYSIS_READ_ERROR",
                severity="review",
                message="Could not read stack-spacing source: %s" % exc,
            )
        ]
    return _analyze_stack_spacing(_mask_literals_and_comments(content))


def analyze_template_spacing_file(file_path: str) -> List[CommonIssue]:
    """Analyze literal vertical stack spacing in a local Typst template."""
    try:
        content = Path(file_path).read_text(encoding="utf-8")
    except Exception as exc:
        return [
            CommonIssue(
                code="SPACING_ANALYSIS_READ_ERROR",
                severity="review",
                message="Could not read template spacing source: %s" % exc,
            )
        ]
    code_content = _mask_literals_and_comments(content)
    return _analyze_stack_spacing(code_content)


def analyze_common_issues(file_path: str) -> List[CommonIssue]:
    """Return conservative source heuristics with stable codes.

    The checks only inspect the requested entry file. They do not follow imports
    or impose the repository's direct Touying version on third-party Universe
    packages. All findings still require source/render context.
    """
    issues: List[CommonIssue] = []
    path = Path(file_path)

    try:
        content = path.read_text(encoding="utf-8")
    except Exception as exc:
        return [
            CommonIssue(
                code="STATIC_READ_ERROR",
                severity="blocker",
                message="Could not read entry file: %s" % exc,
            )
        ]

    code_content = _mask_literals_and_comments(content)
    import_content = _mask_literals_and_comments(content, preserve_import_strings=True)
    issues.extend(_analyze_stack_spacing(code_content))

    if "#import" not in code_content:
        issues.append(
            CommonIssue(
                code="NO_IMPORT_DIRECTIVE",
                severity="advisory",
                message="No #import directive found in the entry file; verify that this is intentional.",
            )
        )
    if "#show" not in code_content:
        issues.append(
            CommonIssue(
                code="NO_SHOW_DIRECTIVE",
                severity="advisory",
                message="No #show directive found in the entry file; verify the presentation entry point.",
            )
        )

    old_api_patterns = (
        (
            r"themes\.\w+\.register\s*\(",
            "themes.*.register() is a legacy Touying API; verify the owning package before migrating.",
        ),
        (
            r"utils\.methods\s*\(",
            "utils.methods() is a legacy Touying API; verify the owning package before migrating.",
        ),
        (
            r"\(s\.methods\.\w+\)",
            "s.methods.* is a legacy Touying API; verify the owning package before migrating.",
        ),
        (
            r"states\.\w+\(\)",
            "states.*() is a legacy Touying API; verify the owning package before migrating.",
        ),
    )
    for pattern, message in old_api_patterns:
        match = re.search(pattern, code_content)
        if match:
            issues.append(
                CommonIssue(
                    code="LEGACY_TOUYING_API",
                    severity="review",
                    message=message,
                    line=_line_for_match(content, match),
                )
            )

    direct_versions = list(
        re.finditer(
            r'#import\s+"@preview/touying:(\d+\.\d+\.\d+)"',
            import_content,
        )
    )
    for match in direct_versions:
        version = match.group(1)
        if _version_tuple(version) < (0, 6, 0):
            issues.append(
                CommonIssue(
                    code="DIRECT_TOUYING_PRE_0_6",
                    severity="advisory",
                    message=(
                        "Direct Touying %s import uses a pre-0.6 API. Review compatibility; "
                        "do not rewrite package-owned dependencies mechanically." % version
                    ),
                    line=_line_for_match(content, match),
                )
            )

    # TCS checks are scoped to the generated project entry. They remain review
    # signals because an intentional one-off element may require human context.
    if path.name == "main.typ":
        tcs_patterns = (
            (
                "TCS_INLINE_COLOR",
                r"\brgb\s*\(",
                "rgb() found in main.typ; prefer a named template palette token.",
            ),
        )
        for code, pattern, message in tcs_patterns:
            match = re.search(pattern, code_content)
            if match:
                issues.append(
                    CommonIssue(
                        code=code,
                        severity="review",
                        message=message,
                        line=_line_for_match(content, match),
                    )
                )

    # breakable:false is only known to be available for a direct Touying 0.7+
    # entry. Third-party packages may own older APIs, so they are deliberately
    # not inferred from a generic occurrence of the word "touying".
    direct_07_plus = any(
        _version_tuple(match.group(1)) >= (0, 7, 0) for match in direct_versions
    )
    if direct_07_plus and not re.search(
        r"\bbreakable\s*:\s*false\b", code_content
    ):
        issues.append(
            CommonIssue(
                code="AUTO_BREAK_REVIEW",
                severity="advisory",
                message=(
                    "Static check found no literal breakable: false in this direct Touying "
                    "0.7+ entry. Verify the effective show-rule configuration and physical "
                    "page count in the rendered output."
                ),
            )
        )

    return issues


def check_common_issues(file_path: str) -> List[str]:
    """Backward-compatible text wrapper around :func:`analyze_common_issues`."""
    return [
        "%s: [%s] %s%s"
        % (
            issue.severity.upper(),
            issue.code,
            issue.message,
            " (line %d)" % issue.line if issue.line is not None else "",
        )
        for issue in analyze_common_issues(file_path)
    ]


def main() -> None:
    """Run the CLI entry point for error lookup."""
    if len(sys.argv) > 1:
        error_type = sys.argv[1]
        context = {}
        for arg in sys.argv[2:]:
            if '=' in arg:
                key, value = arg.split('=', 1)
                context[key] = value

        print(ErrorHelper.format_error_message(error_type, context))
    else:
        ErrorHelper.print_help()


if __name__ == '__main__':
    main()
