// ===============================================================
// Silky Slides INSA — Comprehensive Demo
// Universe package: @preview/silky-slides-insa:0.2.0
// Touying version: 0.7.4 (owned by the Universe package)
//
// This demo showcases all slide types and unique features of the
// INSA engineering school theme: branded title slides (simple and
// visual layouts), section slides with descriptions, INSA brand
// colors, incremental reveals with #pause, custom list markers,
// and the INSA graphic charter typography.
//
// NOTE: Parameters are passed DIRECTLY to insa-slides — NOT
// inside config-info(). This is a key difference from most
// Touying themes.
// ===============================================================

#import "@preview/silky-slides-insa:0.2.0": *
#import "@preview/mitex:0.2.7": *

// --- Theme Configuration ---
// insa-slides takes direct parameters: title, subtitle,
// title-visual, and insa (school identifier).
// Supported insa values: "rennes", "hdf", "cvl"
#show: insa-slides.with(
  // Direct parameters (NOT inside config-info)
  title: "Algorithmique Avancee",
  subtitle: "Marie Dupont -- 4INFO, Semestre 7",
  insa: "rennes",
  // title-visual: none,  // simple layout (default)
)

// The title slide is automatically generated by insa-slides.
// No need to call #title-slide() manually — it's already shown.

// =========================================
// SECTION 1: Theme Overview
// =========================================
// Level-1 headings create branded section slides with the
// INSA slide-section.svg background, 40pt bold title, and
// automatic slide counter in the bottom-right.
= Introduction

== Presentation du theme

Ce theme implemente la charte graphique INSA pour les presentations Touying.

- Arriere-plans SVG officiels de la charte graphique INSA
- Logos automatiques selon l'ecole choisie (`"rennes"`, `"hdf"`, `"cvl"`)
- Typographie conforme : League Spartan (titres) + Source Serif (corps)
- Compteur de slides integre dans le pied de page

== Configuration du theme

#block[
  #set text(size: 14pt)

  Les parametres sont passes *directement* a `insa-slides` :

  ```typst
  #show: insa-slides.with(
    title: "Titre de la presentation",
    subtitle: "Sous-titre ou nom de l'auteur",
    insa: "rennes",  // "rennes", "hdf", ou "cvl"
    // title-visual: image("visual.png"),
  )
  ```

  Ceci differe des autres themes Touying qui utilisent `config-info()`.
]

// =========================================
// SECTION 2: INSA Brand Colors
// =========================================
// Explicit section slide with description — this is a unique
// feature of silky-slides-insa. The description appears below
// the section title in 24pt text.
#section-slide(
  [Couleurs INSA],
  description: [Utilisation des couleurs officielles de la charte graphique],
)

== Palette de couleurs

Les couleurs INSA sont accessibles via le dictionnaire `insa-colors` :

- #box(width: .8em, height: .8em, fill: insa-colors.primary, radius: 2pt)[] `insa-colors.primary` — Rouge INSA (\#e42618)
- #box(width: .8em, height: .8em, fill: insa-colors.secondary, radius: 2pt)[] `insa-colors.secondary` — Or INSA (\#f69f1d)
- #box(width: .8em, height: .8em, fill: insa-colors.tertiary, stroke: .5pt + gray, radius: 2pt)[] `insa-colors.tertiary` — Rose clair (\#f5adaa)

Ces couleurs peuvent etre utilisees n'importe ou dans la presentation :

#align(center)[
  #box(fill: insa-colors.primary, radius: 4pt, inset: 12pt)[
    #text(fill: white, weight: "bold")[Alerte rouge]
  ]
  #h(1em)
  #box(fill: insa-colors.secondary, radius: 4pt, inset: 12pt)[
    #text(fill: black, weight: "bold")[Information]
  ]
  #h(1em)
  #box(fill: insa-colors.tertiary, radius: 4pt, inset: 12pt)[
    #text(weight: "bold")[Note douce]
  ]
]

== Couleurs dans les tableaux

#block[
  #set text(size: 18pt)

  #align(center)[
    #table(
      columns: 4,
      align: (left, center, center, center),
      table.header(
        [*Algorithme*], [*Complexite*], [*Memoire*], [*Stable*],
      ),
      [Tri par insertion], [#mi(`O(n^2)`)], [#mi(`O(1)`)], [Oui],
      [Tri rapide], [#box(fill: insa-colors.secondary, inset: (x: 4pt, y: 1pt), radius: 2pt)[#mi(`O(n \log n)`)]], [#mi(`O(\log n)`)], [Non],
      [Tri fusion], [#text(fill: insa-colors.primary)[#mi(`O(n \log n)`)]], [#mi(`O(n)`)], [Oui],
      [Tri par tas], [#box(fill: insa-colors.secondary, inset: (x: 4pt, y: 1pt), radius: 2pt)[#mi(`O(n \log n)`)]], [#mi(`O(1)`)], [Non],
    )
  ]

  Utilisez les couleurs INSA pour mettre en valeur les resultats cles.
]

// =========================================
// SECTION 3: Incremental Reveals
// =========================================
= Animations

== Affichage progressif

Le package exporte les primitives d'animation de Touying 0.7.4. Utilisez-les seulement lorsque la divulgation progressive sert le contenu, puis verifiez chaque page compilee :

- Premiere etape : definir le probleme
- Deuxieme etape : proposer un algorithme
- Troisieme etape : analyser la complexite

== Liste progressive

- #text(fill: insa-colors.primary)[Etape 1] : Analyser les donnees d'entree
  - Identifier les invariants
  - Verifier les preconditions
- #box(fill: insa-colors.secondary, inset: (x: 4pt, y: 1pt), radius: 2pt)[Etape 2] : Concevoir la solution
  - Choisir la structure de donnees
  - Definir les sous-problemes
- #text(fill: insa-colors.primary)[Etape 3] : Implementer et tester

// =========================================
// SECTION 4: Title Slide Variants
// =========================================
#section-slide(
  [Variantes de slides],
  description: [Le theme propose plusieurs types de slides avec des mises en page specifiques],
)

== Slide de titre avec visuel

On peut inserer une deuxieme page de titre avec un visuel sur la droite.
Le visuel est place dans une zone de 12cm x 11cm a droite :

```typst
#title-slide(
  title: "Nouveau chapitre",
  subtitle: "Avec un visuel a droite",
  title-visual: image("schema.png"),
)
```

// Demonstrate a second title slide with overridden parameters.
// In a real presentation, you would use an actual image.
#title-slide(
  title: "Structures de Donnees",
  subtitle: "Chapitre 3 -- Arbres binaires de recherche",
  title-visual: align(center + horizon)[
    #text(size: 60pt)[#sym.suit.club]
  ],
)

// =========================================
// SECTION 5: Academic Content
// =========================================
= Contenu Academique

== Formules mathematiques

Le theme gere nativement le contenu academique a 22pt :

*Theoreme (Maitre)* : Soit #mi(`T(n) = a T(n/b) + f(n)`) avec #mi(`a \geq 1`) et #mi(`b > 1`).

#mitex(`T(n) = \begin{cases} \Theta(n^{\log_b a}) & \text{si } f(n) = O(n^{\log_b a - \epsilon}) \\ \Theta(n^{\log_b a} \log n) & \text{si } f(n) = \Theta(n^{\log_b a}) \\ \Theta(f(n)) & \text{si } f(n) = \Omega(n^{\log_b a + \epsilon}) \end{cases}`)

*Application :* Le tri fusion a #mi(`a = 2`), #mi(`b = 2`), #mi(`f(n) = \Theta(n)`), donc #mi(`T(n) = \Theta(n \log n)`).

== Listes et marqueurs

#block[
  #set text(size: 18pt)

  Le theme personnalise les marqueurs de liste :

  - Niveau 1 : petit cercle plein (`sym.circle.filled.tiny`)
    - Niveau 2 : signe plus (`sym.plus`)
      - Les sous-niveaux suivent les defauts Typst

  + Les listes numerotees fonctionnent normalement
  + Avec l'indentation attendue
    + Et les sous-niveaux
]

== Code source

#block[
  #set text(size: 14pt)

  ```python
  def tri_fusion(tableau: list[int]) -> list[int]:
      if len(tableau) <= 1:
          return tableau
      milieu = len(tableau) // 2
      gauche = tri_fusion(tableau[:milieu])
      droite = tri_fusion(tableau[milieu:])
      return fusionner(gauche, droite)

  def fusionner(g: list[int], d: list[int]) -> list[int]:
      resultat = []
      i = j = 0
      while i < len(g) and j < len(d):
          if g[i] <= d[j]:
              resultat.append(g[i]); i += 1
          else:
              resultat.append(d[j]); j += 1
      return resultat + g[i:] + d[j:]
  ```
]

// =========================================
// SECTION 6: Advanced Section Slides
// =========================================
// Demonstrating the two ways to create section slides:

// Method 1: Automatic (via level-1 heading, no description)
= Conclusion

== Recapitulatif des fonctionnalites

#block[
  #set text(size: 16pt)

  Ce theme offre des fonctionnalites specifiques a l'INSA :

  + *3 types de slides* -- titre (simple/visuel), section (avec description), contenu
  + *3 ecoles supportees* -- `"rennes"`, `"hdf"`, `"cvl"` avec logos automatiques
  + *Couleurs INSA* -- `insa-colors.primary`, `.secondary`, `.tertiary`
  + *Charte graphique* -- arriere-plans SVG officiels, typographie conforme
  + *`#pause`* -- revelations incrementales Touying
  + *`#section-slide`* -- sections avec descriptions optionnelles
  + *`#title-slide`* -- insertion de pages de titre additionnelles avec visuels
  + *Marqueurs personnalises* -- cercle plein et signe plus
]

== Pour aller plus loin

#block[
  #set text(size: 17pt)

  Ressources utiles :

  - Documentation Touying : https://touying-typ.github.io/touying/
  - Package sur Typst Universe : https://typst.app/universe/package/silky-slides-insa
  - Code source : https://github.com/SkytAsul/INSA-Typst-Template
  - Polices recommandees : dossier `fonts/` du depot GitHub

  Pour contribuer les assets d'une autre ecole INSA, ouvrez une _pull request_ sur le depot GitHub.
]
